name: 'Observe Ingest'
description: 'Ingest a JSON Payload into Observe'
inputs:
  json_data:
    description: 'JSON-encoded data to be submitted'
    required: true
  observe_user_id:
    description: 'Observe User ID'
    required: true
  observe_ingest_token:
    description: 'Observe Ingest Token'
    required: true
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
